    <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="<?php echo URLBASE ?>inicio">Inicio</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<?php echo URLBASE ?>condiciones-de-uso">Conciones de Uso</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<?php echo URLBASE ?>faq">FAQ</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<?php echo URLBASE ?>contacto">Contacto</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<?php echo URLBASE ?>acerca-de">Acerca de</a>
                        </li>
                       <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="<?php echo URLBASE ?>ayuda">Ayuda</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyleft <span class="copy-left">&copy;</span> SISEC <?php echo "2015-". date("Y"); ?>. Software desarrollado bajo estándares abiertos</p>
                </div>
            </div>
        </div>
    </footer>