<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sistema de Evaluación de Calidad">
    <meta name="author" content="Miguel Salazar">
    <link rel="icon" type="image/png" href="<?php echo URLBASE?>public/img/icono.png" />
    <title>SISEC</title>
    <?php include dirname(__FILE__) . "/css.phtml";?>
    <?php include dirname(__FILE__) . "/scripts.phtml";?>
</head>
<body>
<?php 
 $sesion = $_SESSION["sesion_" . $_SESSION["usuario"]];
if ($sesion): 
   $estiloSesion = "id='wrapper'";
    else:
        $estiloSesion = "";
endif;
?>
    <div <?php echo $estiloSesion;?>>
<?php if ($sesion): ?>
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Panel</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo URLBASE?>inicio">
                    <img style="position:relative; top:-4px; left:2%;" src="<?php echo URLBASE; ?>public/img/Logo.png">
                </a>
            </div>
            <?php include dirname(__FILE__) . "/menu-top.phtml";?>
            <?php include dirname(__FILE__) . "/menu-left.phtml";?>
        </nav>
<?php endif?>
        <div id="page-wrapper">
            <div class="container-fluid" style="margin-left:2%;margin-right:2%; padding-bottom: 5%;">
                <div class="row">
                    <?php include "http/controller/controller.php"; ?>
                </div>                
            </div>
        </div>
        <?php include dirname(__FILE__) . "/footer.phtml";?>
    </div>
</body>
</html>
