 <?php
/**
 * =================================================
 * @Descripcion: Vista que muestra el menú superior del software
 * usuario que está en una sesión iniciada
 * @Author: Bootsrap
 * @Adaptado: Miguel Salazar
 * @Fecha: Marzo, 2016
 * @Version: 1.0
 * @E-Mail: miguel__salazar@hotmail.com
 * ==================================================
 * 
 */     
 ?>
    <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">                   
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $_SESSION["nombre"];?><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo URLBASE ?>usuario/cuenta"><i class="fa fa-fw fa-user"></i> Mi Datos</a>
                        </li>
                        <li>
                            <a href="<?php echo URLBASE?>historial/usuario"><i class="fa fa-fw fa-history"></i> Historial</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?php echo URLBASE ?>cerrar"><i class="fa fa-fw fa-power-off"></i> Cerrar Sesión</a>
                        </li>
                    </ul>
                </li>
            </ul>