<style type="text/css">
page {        
    font-family: Arial;
}    
    
* {
    margin:0;
    padding: 0;
    font-size: 12px;
    line-height: 1.3;
}
.banner {
    margin:auto;
    text-align: center;
    width:625px;
    /*border: 1px solid #333;*/
}
.banner img {
    margin:auto;
    text-align: center;
    width:100%;
    height: auto;
}
.titulo {
    margin:auto;
    margin-top:10px;
    text-align: center;
    font-weight: bold;
    
}
.subtitulo {
    font-weight: bold;
    margin:auto;
    text-align: left;
    margin-top:25px;
    margin-bottom:5px;
}
hr {
    border: 0.5px;
    border-color: #f0f0f0;
    padding: 0;
    margin: 0;
}
.contenido {
    width:100%;
    height: auto;
    margin-top: 10px;
}
.grupo {
    margin:auto;
    width: 100%;
    border:1px solid #444;
}
label {
    font-weight: bold;
}


table {
    color: #333;
    border-collapse: collapse;
 }
 
td, th { 
    border: 1px solid transparent; 
    height: 3px;     
    padding: 5px;
}

th {
    width: 35%;
    background: #FAFAFA;
    font-weight: bold; 
}

td { 
    width: 65%;
    text-align: left; 
}

#resultados-generales td, #resultados-generales th { 
    border: 1px solid #f0f0f0; 
    height: 3px;     
    padding: 5px;
}
#resultados-generales th {
    width: 35%;
    background: none;
    font-weight: bold; 
}

#resultados-generales td { 
    width: 65%;
    text-align: left; 
}
#resultados-generales {
    margin-top:5px;
}
.titulo-tabla {
    background: #F5F5F5;
}
.texto-rojo {
    color: #ff1a1a;
}
</style>