<?php
/**
 * =================================================
 * @Descripcion: Vista que permite confirmar la
 * prueba de carga de datos
 * @Author: Miguel Salazar
 * @Fecha: Marzo, 2016
 * @Version: 1.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * ==================================================
 * 
 */ 

include dirname(__FILE__) . "/../../navegacion/navegacionView.phtml";
?>

<div id="dialogo-espera" class="ventana">
    <img src="<?php echo URLBASE; ?>/public/img/preload.gif" alt="jqeury">
    <h3>Por favor espere...</h3>
</div>
<?php
if ($notificacion) {
    echo $notificacion;
}
for($i=0; $i<$configPruebaDeSesion["total_campos"]; $i++) {
    foreach ($configPruebaDeSesion["campos_$i"] as $llave => $valor) {
            $datos[$i][$llave] =  $valor;
    }
}
?>

<div class="panel panel-default">
    <div class="panel-heading">Datos para la la Prueba de Sesión</div>
    <!--<a style="float:right;" href="<?php echo URLBASE ?>configurar-prueba-de-sesion" class="fa fa-edit"> Actualizar Datos</a></div>-->
    <form method="POST">    
        <table class="table table-bordered">
            <tr>
                <th>URL Destino</th>
                <td><?php echo $configPruebaDeSesion["url"]; ?> </td>
            </tr>
            <tr>
                <th>Mensaje de Error</th>
                <td><?php echo $configPruebaDeSesion["cadena_invalida"]; ?> </td>
            </tr>
            <tr>
                <th>Campo de Usuario</th>
                <td><?php echo $configPruebaDeSesion["campo_usuario"]; ?> </td>
            </tr>
            <tr>
                <th>Campo de Contraseña</th>
                <td><?php echo $configPruebaDeSesion["campo_contrasenia"]; ?> </td>
            </tr> 
            <tr>
                <th>Campos Adicionales</th>
                <td>
                    <?php                           
                    foreach($configPruebaDeSesion["campo_adicional"] as $nombre => $valor):
                    ?>
                        <div style="margin-top:1%;">
                        <?php echo $nombre . " = " . $valor; ?>
                        </div>
                    <?php 
                    endforeach;                            
                    ?>

                </td>
            </tr>
            <tr>
                <td colspan="2">Confirmación de la Prueba</td>       
            </tr>
            <tr>
                <th>Diccionario de Usuarios</th>
                <td>
                    <?php if(empty($nombreArchivo["diccionario_de_usuarios"])):
                            echo "<span class='text-danger'>No se seleccionó ningún archivo</span>";
                        else:
                            echo $nombreArchivo["diccionario_de_usuarios"];
                        endif;                            
                    ?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?php
                    if(empty($nombreArchivo["diccionario_de_usuarios"])):
                        $mensaje = 1;
                    endif;

                    if($mensaje == 1): 
                    ?>
                    <span><b>Nota:</b> Si no seleccionó ningún archivo, el sistema creará y adjuntará uno por defecto (<b>100 usuarios</b>)</span>                
                    <?php 
                    endif;
                    ?>
                </td>
            </tr>
                
                <tr class="tr tr-bordered center">
                    <td colspan="2">
                        <span class="text-danger">
                            <span class="fa fa-warning"></span>
                            ¿Está seguro que desea realizar esta prueba?
                            <br>
                            Se le notifica que esta prueba se realiza sólo una vez por cada ciclo de evaluaión
                        </span>
                    </td>
                </tr>
            </table>
        <div class="panel-body center">
            <button type="button" class="btn btn-default" onClick="window.location.href='<?php echo URLBASE?>rendimiento/prueba-de-sesion'">Cancelar</button>
            &nbsp;
            &nbsp;
            <button type="submit" name="confirmar" class="btn btn-default" id="confirmar">Confirmar</button>
        </div>
    </form>
</div>
</div>

<!--<div class="formulario" align="center">-->
<!--
<form class="pure-form pure-form-aligned" method="POST">
    <input type="hidden" name="pagina_referencia" value="<?php echo $_POST["pagina_referencia"]; ?>">
    <input type="hidden" name="id_user" value="<?php echo $_POST["id_user"]; ?>">    
    <fieldset>
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">Datos para la Prueba de Carga Datos</th>
                </tr>
            </thead>
            <tbody>
                <tr>  
                    <td class="td-right">
                        <label for="url">URL Destino</label>
                    </td>
                    <td>
                        <?php echo $configPruebaDeSesion["url"]; ?>                        
                    </td>
                </tr>
                <tr>     
                    <td class="td-right">
                        <label>Mensaje de Éxito</label>
                    </td>
                    <td>
                        <?php echo $configPruebaDeSesion["cadena_valida"]; ?>
                    </td>
                    
                </tr>
            <?php                                
                for($i=0; $i<count($datos);$i++):
            ?>
                <tr>
                    <td  class="td-right">
                        <label>Campos N° <?php echo $i+1; ?></label>
                    </td>
                    <td>
                        <div style="margin-top:1%;">                                    
                        <?php echo "Nombre = " . $datos[$i]["nombre"]; ?>
                        </div>
                        <div style="margin-top:1%;">                                    
                        <?php echo "Tipo = " . $datos[$i]["tipo"]; ?>
                        </div>
                        <div style="margin-top:1%;">                                    
                        <?php echo "Longitud = " . $datos[$i]["longitud"]; ?>
                        </div>
                    </td>
                </tr>
                <?php 
                    endfor;                              
                 if(count($configPruebaDeSesion["campo_adicional"]) > 0):
                ?>
                <tr>
                    <td class="td-right">
                        <label>Campos Adicionales</label>
                    </td>
                    <td>
                        <?php                           
                            foreach($configPruebaDeSesion["campo_adicional"] as $nombre => $valor):
                            ?>
                                <div style="margin-top:1%;">
                                <?php echo $nombre . " = " . $valor; ?>
                                </div>
                            <?php 
                            endforeach;                            
                            ?>
                    </td>
                </tr>
                <?php
                endif;
                ?>
                <tr>
                    <td class='td-right' colspan="2">
                        <a class="glyphicon glyphicon-edit" href="<?php echo URLBASE; ?>configurar-prueba-de-carga">Editar</a>
                    </td>                   
                </tr>
            </tbody>  
            <thead>
                <tr>
                    <th class='mensaje-advertencia' colspan="2">Confirmacón de la Prueba</th>
                </tr>
            </thead>
            <tbody>
                <tr>          
                    <td class="td-right">
                        <label for="email">Cantidad de Cargas</label>
                    </td>
                    <td>
                        <?php
                         echo $_SESSION["cantidad"];                                                          
                        ?>
                    </td>
                </tr>
                <?php
                if (empty($_SESSION["tiempos_personalizados"])):
                ?>
                <tr>          
                    <td class="td-right">
                        <label >Tiempos de Medición</label>
                    </td>
                    <td>
                        <?php
                         echo "<span>Tiempos no personalizados<br>El sistema establecerá los tiempos por defecto</span>";                                                          
                        ?>
                    </td>
                </tr>
                <?php
                else:
                ?>
                <tr>          
                    <td class="td-right">
                        <label for="email">Tiempos de Medición</label>
                    </td>
                    <td>
                        <?php
                         echo "Tiempo Óptimo: " . $_SESSION["optimo"] . " segs. <br>";
                         echo "Tiempo Intermedio: " . $_SESSION["intermedio"] . " segs. <br>";
                         echo "Tiempo Mínimo: " . $_SESSION["minimo"] . " segs.";
                        ?>
                    </td>
                </tr> 
                <?php 
                endif;
                ?>
                 <tr class="tr-center">
                    <td colspan="2">
                        <span class="mensaje-confirmacion">¿Está seguro que desea realizar esta prueba?
                        <BR>Se le notifica que esta prueba se realiza sólo una vez por cada ciclo de evaluaión</span>
                    </td> 
                </tr>

                <tr  class="submit"> 
                    <td  colspan="2" align="center">
                        <input type="button" class="btn btn-danger" value="Cancelar" onClick="history.back();">  

                        <input type="submit" class="btn btn-danger" value="Confirmar" name="confirmar" id="confirmar">
                    </td>
                </tr>
            </tbody>
        </table> 
    </fieldset>    
</form>-->