<?php 
$popoverTituloPeticiones = "Cantidad de Cargas a Realizar";
$popoverContenidoPeticiones = "Número de cargas o registros que se quieren realizar.";

$popoverTituloTiempos = "Personalizar Tiempos";
$popoverContenidoTiempos = "Si remarca esta opción debe configurar los tiempos con los que usted desea realizar la prueba.";

$popoverTituloOptimo = "Tiempo Óptimo";
$popoverContenidoOptimo = "El tiempo medible más corto que desea que el producto alcance.";

$popoverTituloIntermedio = "Tiempo Intermedio";
$popoverContenidoIntermedio = "El tiempo medible de condición normal en el que espera que el producto opere.";

$popoverTituloMinimo = "Tiempo Mínimo Aceptable";
$popoverContenidoMinimo = "El tiempo medible más largo y aceptable que el producto pueda igualar o superar.";

?>