<?php 
$popoverTituloUsuario = "Usuario";
$popoverContenidoUsuario = "Nombre del usuario que se utiliza para acceder al sistema. Campo único.";

$popoverTituloEmail = "E-Mail";
$popoverContenidoEmail = "Correo Electrónico del usuario. Requerido para recuperación de datos y envío de contraseña.";

$popoverTituloNivel = "Nivel de Usuario";
$popoverContenidoNivel = "Es el nivel de priviligio que tendrá el usuario en el sistema.";

$popoverTituloContrasenia = "Nueva Contraseña";
$popoverContenidoContrasenia = "Este campo debe estar conformado por 8 carácteres con mayúsculas, minúsculas y números enteros.";

$popoverTituloNuevaContrasenia = "Nueva Contraseña";
$popoverContenidoNuevaContrasenia = "La contraseña debe ser mayor a 8 carácteres que contengan letras mayúsculas, letras minúsculas y números [AZ-az-09].";

$popoverTituloPregunta = "Pregunta de Seguridad";
$popoverContenidoPregunta = "Es la pregunta de seguridad que se utiliza para recuperar la contraseña en caso de haberla olvidado.";

$popoverTituloRespuesta = "Respuesta de Seguridad";
$popoverContenidoRespuesta = "Es la respuesta de seguridad que se utiliza para recuperar la contraseña en caso de haberla olvidado.";

?>