<?php
/**
 * =============================================================================
 * @Descripcion: Vista para mostrar el listado de los ciclos de evaluaciones
 * @Author: Miguel Salazar
 * @Fecha: Abril, 2016
 * @Version: 1.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * =============================================================================
 * 
 */ 

include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";
if ($notificacion) {
    echo $notificacion;
}
?>
<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Descripcion</th>
            <th>Pruebas</th>
            <th>Creador</th>
            <th>Creación</th>
            <th>Estatus</th>      
            <th>Detalle</th>
        </tr>
    </thead>

    <tbody>
<?php 
        $totalCiclos = count($_ciclo);
	for ($i=0; $i<count($_ciclo); $i++):        
       
            $fechaDeCreacion[$i] = Helper::convertirFechaDdMmAaaa($_ciclo[$i]["fecha_creacion"]);
            $horaDeCreacion[$i] = Helper::convertirHoraA12H($_ciclo[$i]["hora_creacion"]);
            $descripcion[$i] = $_ciclo[$i]["descripcion"];
            $estatus[$i] = $_ciclo[$i]["estatus"];
            $id = $_ciclo[$i]["id"];            
            $modal[$i] = $id;
            $urlPag = URLBASE . "evaluacion/listado/$id";
            $prueba = $_prueba[$i][0]["pruebas"] ? $_prueba[$i][0]["pruebas"] : 0;
            $usuario = $_ciclo[$i]["nombre"];
            if($estatus[$i]) {
                $tituloEstatus = "Abierto";
                $imgEstatus = "<a href='#confirmar' data-toggle='modal' data-target='#confirmar'><span class='fa fa-unlock'></span></a>";
                $idAbierto = $id;
            }
            else {
                $tituloEstatus = "Cerrado";
                $imgEstatus = "<span class='fa fa-lock'></span>";
            }
            //if($prueba > 5) $prueba = 5;
        echo "<tr>
                <td title='".$id."'>".$id."</td>
                <td title='" . $descripcion[$i] . "'>" . $descripcion[$i] . "</td>  "
                . "<td title='".$prueba."'>".$prueba."</td>"
                . "<td title='" . $usuario . "'>$usuario</td>"
                . "<td title='" . $fechaDeCreacion[$i] . " " . $horaDeCreacion[$i] 
                
                . "'>" . $fechaDeCreacion[$i] . " " . $horaDeCreacion[$i] . "</td>
                    
                <td title='" . $tituloEstatus . "'>$imgEstatus</td>    
                <td title='Detalle'><a href='$urlPag' class='glyphicon glyphicon-zoom-in'></a></td>
            </tr>";
	endfor; ?>
    </tbody>
</table>


<!-- Modal -->

<div id="confirmar" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-danger">Confirmación del Cierre del Ciclo de Evaluación</h4>
      </div>
      <div class="modal-body">
          <p class="text-info">¿Está seguro que desea cerrar este ciclo de evaluación?</p>
        <p class="">Se le recuerda que si acepta la operación, no se podrán revertir los cambios.</p>
      </div>
      <div class="modal-footer">
          <form method="POST">
                <input type="hidden" value="<?php echo $idAbierto ?>" name="id">                
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="submit" name="confirmar" class="btn btn-success" >Confirmar</button>
          </form>
      </div>
    </div>

  </div>
</div>

<?php
include dirname(__FILE__) . "/../paginador/paginadorView.phtml";
?>