<?php
/**
 * =================================================
 * @Descripcion: Vista para mostrar el listado del
 *  historial de los usuarios
 * @Author: Miguel Salazar
 * @Fecha: Dic, 2015 - Febrero, 2016
 * @Version: 1
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguel__salazar@hotmail.com
 * ==================================================
 * 
 */ 

?>

<div class="row">
    <div class="col-lg-12">
        <h2>
            <small><?php echo $tema["vista"]; ?></small>
        </h2>
        <ol class="breadcrumb">
            <li class="active">
                <a title="Ir al Inicio" href="<?php echo  URLBASE ?>inicio" <i class="fa fa-home"></i> Inicio </a>
            </li>
            <li class="active">
                <i class="fa fa-<?php echo $tema["icono"]; ?>"></i> <?php echo $tema["actual"]; ?>
            </li>   
        
            <a title="Ir a la página anterior" href="javascript:;" onClick="history.back();">                    
               <img class="btn-volver" src="<?php echo  URLBASE ?>public/img/Button_Back.png">
            </a>
        </ol>
    </div>            
</div>

<div class="row">
    <form class="form-horizontal" role="form" method="post" id="form" 
          action="<?php echo URLBASE; ?>historial/usuarios-por-fecha">
        <div class="col-xs-2">
            <label class="control-label">Filtrar Listado:</label>
        </div>
        <div class="col-md-3">
            <input title="Fecha inicial de la búsqueda" class="form-control" id="fecha_desde" type="text" placeholder="Fecha Inicial" maxlength="10" name="fecha_desde"  autocomplete="off">
        </div>
        
        <div class="col-md-3">
            <input title="Fecha final de la búsqueda" class="form-control" id="fecha_hasta" type="text" placeholder="Fecha Final" maxlength="10" name="fecha_hasta"  autocomplete="off">
        </div>
        <div class="col-md-1">
            <input type="submit" value="Buscar" title="Buscar" class="btn btn-default">
        </div>
    </form>
</div>    
<hr>
<table class="table table-hover" style="margin:auto;">
    <thead>
        <tr>
            <th>Fecha y Hora</th>
            <th>Usuario</th>                      
            <th>IP Cliente</th>
            <th>Actividad</th>
            <th>Detalle</th>            
        </tr>
    </thead>

    <tbody>
<?php 
        $totalHistorial = count($_historial);
	for ($i=0; $i<count($_historial); $i++):
        
            $usuario[$i] = $_historial[$i]["nombre"];
            $ipCliente[$i] = $_historial[$i]["ip_cliente"];
            $isp[$i] = $_historial[$i]["isp"];
            $accion[$i] = $_historial[$i]["accion"];
            $navegador[$i] = $_historial[$i]["navegador"];
            $so[$i] = $_historial[$i]["so"];
            $fecha[$i] = Helper::convertirFechaDdMmAaaa($_historial[$i]["fecha"]);
            $hora[$i] = Helper::convertirHoraA12H($_historial[$i]["hora"]);            
            
            $id = $_historial[$i]["id"];
            
            $modal[$i] = $id;
            $urlPag = $urlActual . "/pagina/" . $params["actual"];
        echo "<tr>
                <td title='" . $fecha[$i] . " " . $hora[$i] . "'>" . $fecha[$i] . " " . $hora[$i] . "</td>
                <td title='" . $usuario[$i] . "'>" . $usuario[$i] . "</td>
                <td title='" . $ipCliente[$i] . "'>" . $ipCliente[$i] . "</td>
                <td title='" . $accion[$i] . "'>" . $accion[$i] . "</td>
                <td title='Detalle'><a href='$urlPag#$id' class='fa fa-search'></a></td>
            </tr>";
	endfor; ?>
    </tbody>
</table>
<?php
include dirname(__FILE__) . "/../paginador/paginadorView.phtml";
?>