<?php
/**
 * =================================================
 * @Descripcion: Vista para actualizar los datos del usuario
 * @Author: Miguel Salazar
 * @Fecha: Dic, 2015 - Febrero, 2016
 * @Version: 1
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguel__salazar@hotmail.com
 * ==================================================
 * 
 */ 

include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";
include dirname(__FILE__) . "/../helper/mensajes.phtml";
?>
<div class="panel panel-default" >
    <div class="panel-heading">Datos Actualizables del Usuario</div>
  <div class="panel-body">
            <div class="col-lg-12" >
                <form class="form-horizontal" role="form" method="post" id="form">
                  <div class="form-group">
                    <label for="usuario" class="col-lg-3 control-label">Nombre de Usuario</label>
                    <div class="col-lg-5">
                      <input disabled type="text" class="form-control" id="usuario"
                             placeholder="Nombre de Usuario" name="usuario"
                             value="<?php echo $_usuario[0]["nombre"]?>">
                    </div>
                    <div class="col-lg-4">
                        
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="usuario" class="col-lg-3 control-label">Nombre Completo</label>
                    <div class="col-lg-5">
                      <input type="text" class="form-control" id="nombre"
                             placeholder="Nombre Completo" name="nombre"
                             value="<?php echo $_usuario[0]["nombre_completo"]?>"
                             maxlength="80">
                    </div>
                    <div class="col-lg-4">
                        <label for="usuario" class="control-label text-danger">Requerido</label>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="contrasenia_actual" class="col-lg-3 control-label">Nueva Contraseña</label>
                    <div class="col-lg-5">
                      <input type="password" class="form-control" id="contrasenia_actual" 
                             placeholder="Nueva Contraseña" name="nueva_contrasenia">  
                      <!--<p class="help-block text-primary"><i class="fa fa-question-circle text-primary"></i> 
                          <small class="text-primary">Mímimo 8 caráteres con mayúsculas, minúsculas y números</small></p>-->
                    </div>
                    <div class="col-lg-4">
                        <a class="fa fa-question-circle" href="#" title="<?php echo $popoverTituloContrasenia; ?>" data-toggle="popover" data-placement="right" data-content="<?php echo $popoverContenidoContrasenia; ?>"></a>
                    </div>                    
                  </div>

                  <div class="form-group">
                    <label for="contrasenia2" class="col-lg-3 control-label">Repite la Contraseña</label>
                    <div class="col-lg-5">
                      <input type="password" class="form-control"  
                             placeholder="Repita la Contraseña" name="contrasenia2">
                    </div>
                    <div class="col-lg-4">
                      
                    </div>  
                  </div> 

                  <div class="form-group">
                    <label for="email" class="col-lg-3 control-label">Correo Electrónico</label>
                    <div class="col-lg-5">
                      <input type="text" class="form-control" id="email" 
                             placeholder="Correo Electrónico" name="email"
                             value="<?php echo $_usuario[0]["email"] ?>"
                             maxlength="50">
                    </div>
                    <div class="col-lg-4">
                       <label for="usuario" class="control-label text-danger">Requerido</label>
                    </div>  
                  </div>
                  <div class="form-group">
                    <label for="telefono" class="col-lg-3 control-label">Teléfono de Contacto</label>
                    <div class="col-lg-5">
                      <input type="text" class="form-control" id="telefono"
                             placeholder="Teléfono de Contacto" name="telefono"
                             value="<?php echo $_usuario[0]["telefono"]?>"
                             maxlength="12">
                    </div>
                    <div class="col-lg-4">
                        
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="email" class="col-lg-3 control-label">Nivel del Usuario</label>
                    <div class="col-lg-5">
                      <input disabled type="text" class="form-control" id="usuario"
                             placeholder="Nombre de Usuario" name="usuario"
                             value="<?php echo $_usuario[0]["nivel_usuario"]?>">
                    </div>
                    <div class="col-lg-4">
                        
                    </div>  
                  </div> 
                    
                  <div class="form-group">
                    <label for="email" class="col-lg-3 control-label">Pregunta de Seguridad</label>
                    <div class="col-lg-5 ">
                      <input type="text" class="form-control" id="pregunta"
                             placeholder="Pregunta de Seguridad" name="pregunta"
                             value="<?php echo Helper::decrypt($_usuario[0]["pregunta_secreta"], $_SESSION["id_usuario"])?>">
                    </div>
                    <div class="col-lg-4">
                        <a class="fa fa-question-circle" href="#" title="<?php echo $popoverTituloPregunta; ?>" data-toggle="popover" data-placement="right" data-content="<?php echo $popoverContenidoPregunta; ?>"></a>
                    </div>  
                  </div> 
                  <div class="form-group">
                    <label for="email" class="col-lg-3 control-label">Respuesta de Securidad</label>
                    <div class="col-lg-5">
                      <input type="text" class="form-control" id="respuesta"
                             placeholder="Respuesta de Seguridad" name="respuesta"
                             value="<?php echo Helper::decrypt($_usuario[0]["respuesta_secreta"], $_SESSION["id_usuario"]) ?>">
                    </div>
                    <div class="col-lg-4">
                        <a class="fa fa-question-circle" href="#" title="<?php echo $popoverTituloRespuesta; ?>" data-toggle="popover" data-placement="right" data-content="<?php echo $popoverContenidoRespuesta; ?>"></a>
                    </div>  
                  </div> 
                    
                    
                  <div class="form-group">
                    <label for="contrasenia_actual" class="col-lg-3 control-label">Contraseña Actual</label>
                    <div class="col-lg-5">
                      <input type="password" class="form-control" id="contrasenia" 
                             placeholder="Contraseña Actual" name="contrasenia_actual">  
                      <p class="help-block text-danger"><i class="fa fa-info-circle text-danger"></i> 
                          <small class="text-danger">Campo requerido para guardar los nuevos cambios</small></p>
                    </div>
                    <div class="col-lg-4">
                      <label for="usuario" class="control-label text-danger">Requerido</label>
                    </div>                    
                  </div>
                   
                  <div class="form-group">
                      
                    <div class="col-lg-offset-3 col-lg-9 ">
                        
                      <button type="button" class="btn btn-default" onClick="window.location.href='<?php echo URLBASE ?>usuario/cuenta'">Cancelar</button>
                      &nbsp;
                      &nbsp;
                      <button type="submit" name="actualizar" class="btn btn-default">Actualizar</button>
                    </div>
                  </div>
                </form>
            </div>            
      </div>
</div>
