<?php
/**
 * =================================================
 * @Descripcion: Vista para preparar los datos de la
 * prueba de carga
 * @Author: Miguel Salazar
 * @Fecha: Marzo, 2016
 * @Version: 1.3
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguel__salazar@hotmail.com
 * ==================================================
 * 
 */ 
include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";

if ($notificacion) {
    echo $notificacion;
}

?>
<div class="panel panel-default" >
    <div class="panel-heading">Datos para Crear el Diccionario de Usuarios</div>
        <div class="panel-body">
            <div class="col-lg-12" >
                <form class="form-horizontal" role="form" method="post" id="form">
                  <div class="form-group">
                    <label for="usuario" class="col-lg-3 control-label">Cantidad de Usuarios</label>
                    <div class="col-lg-5">
                      <input autocomplete="off" type="number" class="form-control" id="cantidad"
                             placeholder="Cantidad de Usuarios" name="cantidad"
                             value="1" min="1" max="9999" maxlength="4"
                             value="<?php if(empty($_POST["cantidad"])) 
                                            {echo $configMultiUsuarioParte1["cantidad"];} 
                                            else {echo $_POST["cantidad"];} ?>" 
                             class="solo-numeros-enteros">
                      <p class="help-block text-primary"><i class="fa fa-info-circle text-primary"></i> 
                          <small class="text-primary">Esta es la cantidad de usuarios que se desea crear. 
                          (Disponible sólo para SIRAH)
                          </small>
                      </p>
                    </div>                    
                  </div>
                  <div class="form-group">                      
                    <div class="col-lg-offset-3 col-lg-9 ">        
                      <button type="submit" name="continuar" class="btn btn-default">Continuar</button>
                    </div>
                  </div>
                </form>
            </div>
        </div>
</div>