<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>
<div class="tema-sistema"><a href="<?php echo URLBASE; ?>inicio"><?php echo strtoupper($configSistema["nombre"]); ?></a>
    <span class="glyphicon glyphicon-triangle-right"></span>
    <span class="sub-tema"><?php echo $tema; ?></span>
</div>

<?php
if ($notificacion) {
    echo $notificacion;
}
    include dirname(__FILE__) . '/forms/parte_1.phtml';

?>
