<?php
/**
 * =============================================================================
 * @Descripcion: Vista que muestra el resultado final con los usuarios creados
 * de usuarios
 * @Author: Miguel Salazar
 * @Fecha: Marzo, 2016
 * @Version: 1.3
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * =============================================================================
 * 
 */


include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";


if(!$error):
?>
<div class="panel panel-default">
    <div class="panel-heading">Usuarios creados de forma automática en el sistema de evaluación</div>
        <table class="table">
<?php 
            echo $_SESSION["resultados_de_prueba"];
?>
        </table>
</div>    
 
    <div class="col-lg-12 center">
            <table class="table table-bordered">
                <tr>
                    <td>
                        <a title="Enlace para descarga los resultados de la prueba" 
                           href="<?php echo $_SESSION["ruta_de_archivo"]; ?>" 
                           download="Diccionario de Usuarios.txt">
                            Diccionario de Usuarios
                            <span href="#" class="glyphicon glyphicon-save"></span>
                        </a>
                    </td>
                    <td>
                        <a title="Ir a crear otro diccionario de usuarios" 
                           href="<?php URLBASE; ?>cantidad-de-usuarios">
                           
                            Generar Otro Diccionario
                            <span href="#" class="fa fa-file-text-o"></span>
                        </a>
                    </td>
                    <td>
                        <a title="Redirecciona al sistema en evaluación" target="_blanck" 
                           href="<?php echo $configSistemaEnEvaluacion["url"]; ?>">
                            Ir al sistema en evaluación
                            <span href="#" class="glyphicon glyphicon-globe"></span>
                        </a>
                    </td>
                    <td>
                        <a title="Salir de éste sitio" href="<?php echo URLBASE . "inicio"; ?>">Salir de aquí
                            <span href="#" class="glyphicon glyphicon-remove-circle"></span>
                        </a>
                    </td>
                </tr>
            </table>
    </div>
<?php

else:
    echo $notificacion;
endif;
?>