<?php
/**
 * =============================================================================
 * @Descripcion: Vista que permite configurar los datos de la prueba de inyección xss
 * o el sistema evaluado
 * @Author: Miguel Salazar
 * @Fecha: Dic, 2015 - Marzo, 2016
 * @Version: 1.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguel__salazar@hotmail.com
 * ============================================================================
 * 
 */

include dirname(__FILE__) . "/../../navegacion/navegacionView.phtml";
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST" enctype="multipart/form-data">
    <fieldset>
        
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">Configuración de la Prueba de Inyección SQL</th>
                </tr>
            </thead>
            <tbody>
                <tr>  
                    <td class="td-right">
                        <label for="url">URL Destino</label>
                    </td>
                    <td>
                        <input type="text" placeholder="http://localhost/sirah/" 
                               maxlength="150" name="url" value="<?php if(empty($_POST["url"])) {echo $configSQL["url"];} else {echo $_POST["url"];} ?>" class="solo-albabeto-espaniol-sin-espacio">
   
                        <a href="#" title="<?php echo $popoverTituloUrl; ?>" data-toggle="popover" data-placement="right" data-content="<?php echo $popoverContenidoUrl; ?>"  class="fa fa-question-circle"></a>
                    </td>
                </tr>
                <tr>     
                    <td class="td-right">
                        <label for="password">Mensaje de Error</label>
                    </td>
                    <td>
                        <textarea placeholder="Usuario o contraseña incorrecto" 
                                  maxlength="150" name="cadena_invalida" ><?php if(empty($_POST["cadena_invalida"])) {echo $configSQL["cadena_invalida"];} else {echo $_POST["cadena_invalida"];} ?></textarea>
    
                        <a href="#" title="<?php echo $popoverTituloError; ?>" 
                           data-toggle="popover" data-placement="right" data-content="<?php echo $popoverContenidoError; ?>"  class="fa fa-question-circle"></a>
                    </td>
                    
                </tr> 
                <tr class="tr-center">         
                    <td colspan="2" align='center'>
                        <a onClick="agregarCampoPrincipal();" id="agregarCampoPrincipal" class="btn btn-info" href="#">Agregar Campo</a>
                        <a href="#" title="<?php echo $popoverTituloCampoPrincipal; ?>" data-toggle="popover" 
                           data-placement="right" data-content="<?php echo $popoverContenidoCampoPrincipal; ?>"  class="fa fa-question-circle"></a>
                    </td>
                </tr>
                <tr class="tr-center">
                    <td colspan="2">
                        <div id="contenedor1">
                            <div class="added">
                        <?php                                
                            foreach($configSQL["campo"] as $llave => $valor):
                    ?>
                                <div style="margin-top:1%;">                                    
                                <input class="campos-config" value="<?php echo $llave; ?>" type="text" name="nombre_campo[]" id="campo_1" placeholder="Nombre del Campo N° 1"/>
                                <a title="Eliminar" href="#" class="glyphicon glyphicon-remove"></a>
                                </div>
                        <?php 
                            endforeach;                              
                        ?>
                            </div>
                        </div>
                    </td>
                </tr>               
                <tr class="tr-center">         
                    <td colspan="2">
                        <a id="agregarCampo" class="btn btn-info" href="#">Agregar Campo Adicional</a>  
                        <a href="#" title="<?php echo $popoverTituloCampoAdicional; ?>" data-toggle="popover" 
                           data-placement="right" data-content="<?php echo $popoverContenidoCampoAdicional; ?>"  class="fa fa-question-circle"></a>                        
                    </td>
                </tr>               
                    
                
                <tr class="tr-center">
                    <td colspan="2">
                        <div id="contenedor">
                            <div class="added">
                        <?php
                            if(count($configSQL["campo_adicional"]) > 0):
                                foreach($configSQL["campo_adicional"] as $nombre => $valor):
                                ?>
                                    <div style="margin-top:1%;">
                                    <input class="campos-config" type="text" value="<?php echo $nombre; ?>" name="nombre_campo_adicional[]" id="campo_1" placeholder="Nombre del Campo N° '+ FieldCount +'" /> 
                                    <input class="campos-config" type="text" value="<?php echo $valor; ?>" name="valor_campo_adicional[]" id="campo_2" placeholder="Valor del Campo N° '+ FieldCount +'"/>
                                    <a title="Eliminar" href="#" class="glyphicon glyphicon-remove" id="eliminar-campo"></a>
                                    </div>
                                <?php 
                                endforeach;
                            endif;
                                ?>
                            </div>
                        </div>
                    </td>
                </tr>          
                <tr class="submit">
                    <td  colspan="2" align="center">
                        <input type="button" class="btn btn-default" value="Cancelar" onClick="window.location='<?php echo URLBASE; ?>configurar/evaluacion'">
                        <input type="submit" class="btn btn-default" value="Guardar" name="guardar">
                    </td>                   
                </tr>
            </tbody>  
        </table>
    </fieldset>
</form>
