<?php
/**
 * =============================================================================
 * @Descripcion: Vista que permite configurar los datos básicos de la evaluación
 * o el sistema evaluado
 * @Author: Miguel Salazar
 * @Fecha: Dic, 2015 - Marzo, 2016
 * @Version: 1.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguel__salazar@hotmail.com
 * ============================================================================
 * 
 */

include dirname(__FILE__) . "/../../navegacion/navegacionView.phtml";
if ($notificacion) {
    echo $notificacion;
}
?>
<form class="pure-form pure-form-aligned" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="MAX_FILE_SIZE" value="512">
    <fieldset>
        
        <table class="pure-table pure-table-bordered" id="formulario">
            <thead>
                <tr>
                    <th colspan="2">Datos Generales</th>
                </tr>
            </thead>
            <tbody>
                <tr>  
                    <td align="right">
                        <label for="url">URL del Sistema</label>
                    </td>
                    <td>
                        <input type="text" placeholder="http://sirah.no-ip.org" maxlength="150" name="url" value="<?php if(empty($_POST["url"])) {echo $configSistemaEnEvaluacion["url"];} else {echo $_POST["url"];} ?>" class="solo-albabeto-espaniol-sin-espacio">
                        <a href="#" title="¿Qué es esto?" class="glyphicon glyphicon-question-sign" ></a>
                    </td>
                </tr>
                <tr>  
                    <td align="right">
                        <label for="url">Nombre del Sistema</label>
                    </td>
                    <td>
                        <input type="text" placeholder="SIRAH" maxlength="150" name="nombre" value="<?php if(empty($_POST["nombre"])) {echo $configSistemaEnEvaluacion["nombre"];} else {echo $_POST["nombre"];} ?>" class="solo-albabeto-espaniol-sin-espacio">
                        <!--<img  title="¿Qué es esto?" onClick="return openWindow('box-nombre');" id="<?php echo $llave; ?>" class="icono-ayuda" src="<?php echo URLBASE . "public/img/ayuda-2.png"; ?>">                        -->
                    </td>
                </tr>    
                <tr>  
                    <td align="right">
                        <label for="url">Versión del Sistema</label>
                    </td>
                    <td>
                        <input type="text" placeholder="0.5" maxlength="150" name="version" value="<?php if(empty($_POST["version"])) {echo $configSistemaEnEvaluacion["version"];} else {echo $_POST["version"];} ?>" class="solo-albabeto-espaniol-sin-espacio">
                        <!--<img  title="¿Qué es esto?" onClick="return openWindow('box-nombre');" id="<?php echo $llave; ?>" class="icono-ayuda" src="<?php echo URLBASE . "public/img/ayuda-2.png"; ?>">                        -->
                    </td>
                </tr>
                <thead>
                <tr>
                    <th colspan="2">Datos de Inicio de Sesión</th>
                </tr>
            </thead>
            <tbody>  
		<tr>
                    <td align="right">
                        <label for="url_sesion">URL de Sesión</label>
                    </td>
                    <td>
                        <input type="text" placeholder="http://sirah.no-ip.org/login" maxlength="150" name="url_sesion" value="<?php if(empty($_POST["url_sesion"])) {echo $configSistemaEnEvaluacion["url_sesion"];} else {echo $_POST["url_sesion"];} ?>" class="solo-albabeto-espaniol-sin-espacio">
                        <a href="#" title="¿Qué es esto?" class="glyphicon glyphicon-question-sign" ></a>
                    </td>
                </tr>
		<tr>
                    <td align="right">
                        <label for="url_sesion">Mensaje de Error</label>
                    </td>
                    <td>
                        <input type="text" placeholder="Datos invalidos" maxlength="150" name="mensaje_de_error" value="<?php if(empty($_POST["mensaje_de_error"])) {echo $configSistemaEnEvaluacion["mensaje_de_error"];} else {echo $_POST["mensaje_de_error"];} ?>" class="solo-albabeto-espaniol-sin-espacio">
                        <a href="#" title="¿Qué es esto?" class="glyphicon glyphicon-question-sign" ></a>
                    </td>
                </tr>                
                <tr class="submit">         
                    <td colspan="2">
                        <a id="agregarCampo" class="btn btn-info" href="#">Agregar Campo de Sesión</a>
                        <a href="#" title="¿Qué es esto?" class="glyphicon glyphicon-question-sign" ></a>
                    </td>
                </tr>               
                <tr class="submit">
                    <td colspan="2">
                        <div id="contenedor">
                            <div class="added">
                        <?php
                            if(count($configSistemaEnEvaluacion["login"]) > 0):
                                foreach($configSistemaEnEvaluacion["login"] as $llave => $valor):
                                ?>
                                    <div style="margin-top:1%;">
                                    <input class="campos-config" type="text" value="<?php echo $llave; ?>" name="nombre_campo_adicional[]" id="campo_1" placeholder="Nombre del Campo N° '+ FieldCount +'" /> 
                                    <input class="campos-config" type="text" value="<?php echo $valor; ?>" name="valor_campo_adicional[]" id="campo_2" placeholder="Valor del Campo N° '+ FieldCount +'"/>
                                    <a title="Eliminar" href="#" class="glyphicon glyphicon-remove" id="eliminar-campo"></a>
                                    </div>
                                <?php 
                                endforeach;
                            endif;
                                ?>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr class="submit">
                    <td  colspan="2" align="center">
                        <input type="button" class="btn btn-default" value="Cancelar" 
                               onClick="window.location='<?php echo URLBASE; ?>configurar/evaluacion'">
                        <input type="submit" class="btn btn-default" value="Guardar" name="guardar">
                    </td>                   
                </tr>
            </tbody>  
        </table>
    </fieldset>
</form>
