<?php
/**
 * =============================================================================
 * @Descripción: Vista que muestra los detalles del producto software
 * @Autor: Miguel Salazar
 * @Fecha:  Abril, 2016
 * @Version: 1.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * ============================================================================= * 
 * 
 */
include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";
?>

<div class="jumbotron">
    <div class="form-group">
        <strong>Nombre: </strong><span>SISEC</span>
    </div>
    <div class="form-group">
        <strong>Versión: </strong><span>1.0 BETA</span>
    </div>
    <div class="form-group">
        <strong>Lanzamiento: </strong><span>En espera</span>
    </div>
    <div class="form-group">
        <strong>Diseño y Desarrollo: </strong><span>Miguel Ángel Salazar Castillo</span>
    </div>
    <div class="form-group">
        <small>Producto software cronstruido en software libre con estándares abiertos.</small>
    </div>
</div>