<?php
/**
 * =============================================================================
 * @Descripción: Vista de inicio del software
 * @Autor: Miguel Salazar
 * @Fecha:  Febrero, 2016
 * @Version: 2.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * ============================================================================= * 
 * 
 */
include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";
?>

<div class="container">            
  
    <strong class="text-danger">¡ES UNA PENA! Pero actualmente SISEC no dispone de ayuda en línea</strong>
    <BR>
    <BR>
    <span class="">Disponible Ayuda en formato PDF <i class=""></i></span>
    <a href="<?php echo URLBASE ?>files/downloads/manual-de-ayuda.pdf" download="Manual de Ayuda.pdf"><i class="fa fa-file-pdf-o"></i> Descargar </a>
 

</div>

