<?php
/**
 * =============================================================================
 * @Descripción: Vista de inicio del software
 * @Autor: Miguel Salazar
 * @Fecha:  Febrero, 2016
 * @Version: 2.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * ============================================================================= * 
 * 
 */
include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";
?>

<div class="container">            
    <h2><small>Para cualquier duda o información, comunicarse a los siguientes correos electrónicos de contacto:</small></h2>
    <h3><span class="label label-default">miguelangel.bux@gmail.com</span></h3>
    <h3><span class="label label-default">miguel__salazar@hotmail.com</span></h3>
</div>

