<?php
/**
 * =============================================================================
 * @Descripción: Vista de inicio del software
 * @Autor: Miguel Salazar
 * @Fecha:  Febrero, 2016
 * @Version: 2.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * ============================================================================= * 
 * 
 */
include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";
?>

<div style="img-inicio">            
    <img style="margin:auto;" class="img-responsive" src="<?php echo URLBASE; ?>public/img/inicio.png">           
</div>

