<?php
/**
 * =============================================================================
 * @Descripción: Vista que muestra las preguntas y respuestas secretas del software
 * @Autor: Miguel Salazar
 * @Fecha:  Abril, 2016
 * @Version: 1.0
 * @Licencia: Libre uso GNU-GPL 
 * @E-Mail: miguelangel.bux@gmail.com
 * ============================================================================= * 
 * 
 */
include dirname(__FILE__) . "/../navegacion/navegacionView.phtml";
?>

<ul class="list-group">
  <li class="list-group-item">
        <label>OBJETO</label>
        <p class="help-block text-primary">
        Las presentes Condiciones de Uso (en adelante, las "Condiciones Generales") regulan el uso del producto software SISEC,
       lo cual se pone a disposición de las personas que lo utilicen, facilitarles el acceso y uso a los mismos con fines de honestidad y buenos principios.
        </p>

        
  </li>
  <li class="list-group-item">
        <label>ACCESO Y SEGURIDAD</label>
        <p class="help-block text-primary">
        El acceso a SISEC requiere el registro previo a los usuarios, 
        una vez que se registran y hacen uso del mismo, pasan a ser considerados como Clientes.
        </p>
        
        <p class="help-block text-primary">
           El identificador del Cliente estará compuesto por su nombre de usuario
           y una contraseña. Para el acceso a la cuenta propia del Cliente, será necesario la inclusión de este identificador, 
           así como de una contraseña que deberá contener como mínimo 8 caracteres alfanuméricos.
        </p>
        
  </li>
    
  <li class="list-group-item">
        <label>UTILIZACIÓN CORRECTA DEL PRODUCTO SOFTWARE</label>
        <p class="help-block text-primary">
        El Cliente se obliga a usar el Software de forma diligente, correcta y lícita y, se compromete a abstenerse de:
        </p> 
        <div class="container">
        <ul >
            <li><p class="help-block text-primary"> 
                    Utilizar SISEC con fines o efectos contrarios a la ley, 
                    a la moral y a las buenas costumbres generalmente aceptadas o al orden público.
                </p>
            </li>
            <li><p class="help-block text-primary"> 
                    Reproducir, copiar, distribuir, transformar o modificar el programa sin dar a conocer los correspondientes derechos del desarrollador
                    que se enmarca en los estándares de software libre;
                </p>
            </li>            
        </ul>
        </div>
        <p class="help-block text-primary">
            El Cliente responderá de los daños y perjuicios de toda naturaleza que SISEC pueda sufrir, 
            con ocasión o como consecuencia del incumplimiento de cualquiera de las obligaciones anteriormente expuestas 
            así como cualesquiera otras incluidas en las presentes Condiciones Generales y/o las impuestas por la Ley en relación con la utilización del Software.
        </p>
  </li>
 
</ul>
